# version: "3.8"

services:
  db:
    container_name: db
    build:
      context: ./Database_Server
    healthcheck:
      test: ["CMD", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - backend-network

  integration-server:
    container_name: Integration_Server
    networks:
      - backend-network
    build:
      context: ./Integration_Server
      dockerfile: Dockerfile
    command: sh -c "python3 /app/database_initialize.py --password=defaultpassword"
    depends_on:
      - db
    restart: always
    ports:
      - "3000:5000"

  analytics-server:
    container_name: analytics-server
    networks:
      - backend-network
    build:
      context: ./Analytics_AI
      dockerfile: Dockerfile
    depends_on:
      - db
      - integration-server
    restart: always

networks:
  backend-network:
    driver: bridge
